### ISSUE TITLE
Smoke Tests fail on Windows

### ISSUE THREAD

**Issue by chirino** [tdiesler/fabric8poc#26]
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running io.fabric8.core.utils.ConfigInjectionUtilsTest
log4j:ERROR Could not read configuration file from URL [file://C:/Users/chirino/sandbox/fabric8poc/itests/smoke/embedded/src/test/resources/logging.properties].
java.net.UnknownHostException: C
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:157)
        at java.net.Socket.connect(Socket.java:579)
        at java.net.Socket.connect(Socket.java:528)
        at sun.net.ftp.impl.FtpClient.doConnect(FtpClient.java:943)
        at sun.net.ftp.impl.FtpClient.tryConnect(FtpClient.java:903)
        at sun.net.ftp.impl.FtpClient.connect(FtpClient.java:998)
        at sun.net.ftp.impl.FtpClient.connect(FtpClient.java:984)
        at sun.net.www.protocol.ftp.FtpURLConnection.connect(FtpURLConnection.java:294)
        at sun.net.www.protocol.ftp.FtpURLConnection.getInputStream(FtpURLConnection.java:393)
        at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:524)
        at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:483)
        at org.apache.log4j.LogManager.<clinit>(LogManager.java:127)
        at org.slf4j.impl.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:64)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:270)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:281)
        at io.fabric8.core.utils.ConfigInjectionUtils.<clinit>(ConfigInjectionUtils.java:25)
        at io.fabric8.core.utils.ConfigInjectionUtilsTest.testNormalizePropertiesWithPrefixes(ConfigInjectionUtilsTest.java:38)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
log4j:ERROR Ignoring configuration file [file://C:/Users/chirino/sandbox/fabric8poc/itests/smoke/embedded/src/test/resources/logging.properties].
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 7.004 sec - in io.fabric8.core.utils.ConfigInjectionUtilsTest
Running io.fabric8.test.smoke.embedded.BasicContainerLifecycleTest
log4j:WARN No appenders could be found for logger (org.jboss.gravia.runtime).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 26.145 sec <<< FAILURE! - in io.fabric8.test.smoke.embedded.BasicContainerLifecycleTest
io.fabric8.test.smoke.embedded.BasicContainerLifecycleTest  Time elapsed: 26.145 sec  <<< ERROR!
java.lang.RuntimeException: Cannot obtain service: io.fabric8.spi.BootstrapComplete
        at org.jboss.gravia.runtime.ServiceLocator.awaitService(ServiceLocator.java:107)
        at org.jboss.gravia.runtime.ServiceLocator.awaitService(ServiceLocator.java:79)
        at io.fabric8.test.embedded.support.EmbeddedTestSupport.beforeClass(EmbeddedTestSupport.java:52)
        at io.fabric8.test.smoke.embedded.BasicContainerLifecycleTest.beforeClass(BasicContainerLifecycleTest.java:61)

Running io.fabric8.test.smoke.embedded.BasicProfilesTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 29.421 sec <<< FAILURE! - in io.fabric8.test.smoke.embedded.BasicProfilesTest
io.fabric8.test.smoke.embedded.BasicProfilesTest  Time elapsed: 29.421 sec  <<< ERROR!
java.lang.RuntimeException: Cannot obtain service: io.fabric8.spi.BootstrapComplete
        at org.jboss.gravia.runtime.ServiceLocator.awaitService(ServiceLocator.java:107)
        at org.jboss.gravia.runtime.ServiceLocator.awaitService(ServiceLocator.java:79)
        at io.fabric8.test.embedded.support.EmbeddedTestSupport.beforeClass(EmbeddedTestSupport.java:52)
        at io.fabric8.test.smoke.embedded.BasicProfilesTest.beforeClass(BasicProfilesTest.java:38)

Running io.fabric8.test.smoke.embedded.ComplexContainerTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 31.683 sec <<< FAILURE! - in io.fabric8.test.smoke.embedded.ComplexContainerTest
io.fabric8.test.smoke.embedded.ComplexContainerTest  Time elapsed: 31.683 sec  <<< ERROR!
java.lang.RuntimeException: Cannot obtain service: io.fabric8.spi.BootstrapComplete
        at org.jboss.gravia.runtime.ServiceLocator.awaitService(ServiceLocator.java:107)
        at org.jboss.gravia.runtime.ServiceLocator.awaitService(ServiceLocator.java:79)
        at io.fabric8.test.embedded.support.EmbeddedTestSupport.beforeClass(EmbeddedTestSupport.java:52)
        at io.fabric8.test.smoke.embedded.ComplexContainerTest.beforeClass(ComplexContainerTest.java:65)
```

**Comment by tdiesler** [comment]
what is the right log4j config url for windows?
